name: Create Salesforce test badges

#inputs:
#  gistid:
#    description: ID of the Gist in which to publish results
#    required: true
#  gisttoken:
#    description: Auth token to update that Gist
#    required: true

outputs:
  testresults_badge_label:
    value: "${{ steps.testresults.outputs.badge_label }}"
  testresults_badge_color:
    value: "${{ steps.testresults.outputs.badge_color }}"
  codecoverage_badge_label:
    value: "${{ steps.codecoverage.outputs.badge_label }}"
  codecoverage_badge_color:
    value: "${{ steps.codecoverage.outputs.badge_color }}"
  pmd_badge_label:
    value: "${{ steps.pmd.outputs.badge_label }}"
  pmd_badge_color:
    value: "${{ steps.pmd.outputs.badge_color }}"
  healthcheck_badge_label:
    value: "${{ steps.healthcheck.outputs.badge_label }}"
  healthcheck_badge_color:
    value: "${{ steps.healthcheck.outputs.badge_color }}"

runs:
  using: "composite"
  steps:

    - name: Get Test Results
      id: testresults
      shell: bash
      run: |
        echo "::set-output name=badge_label::`bash ${{ github.action_path }}/scripts/testresults_badge_label.sh ./reports/codecoverage.json`"
        echo "::set-output name=badge_color::blue"

    - name: Get Code Coverage
      id: codecoverage
      shell: bash
      run: |
        echo "::set-output name=badge_label::`bash ${{ github.action_path }}/scripts/codecoverage_badge_label.sh ./reports/codecoverage.json`"
        echo "::set-output name=badge_color::orange"

    - name: Get PMD Analysis
      id: pmd
      shell: bash
      run: |
        echo "::set-output name=badge_label::`bash ${{ github.action_path }}/scripts/pmd_badge_label.sh ./reports/pmd.json`"
        echo "::set-output name=badge_color::green"

    - name: Get Health Check
      id: healthcheck
      shell: bash
      run: |
        echo "::set-output name=badge_label::`bash ${{ github.action_path }}/scripts/healthcheck_badge_label.sh ./reports/healthcheck.json`"
        echo "::set-output name=badge_color::darkblue"

