name: Create Salesforce test badges

# Parameters : 
#    secrets.DYNAMIC_BADGES_GIST_TOKEN
#    gistID: 18badd1cddae0dabd361d6235f49b77c
#    scripts
#    4 test reports data files
#
#       AUTH:      525d549245608cc0cf0e7c7860d4a9bd5f9dc36d
#       GIST_ID:   18badd1cddae0dabd361d6235f49b77c

inputs:
  gistid:
    description: ID of the Gist in which to publish results
    required: true
  gisttoken:
    description: AUth token to update that Gist
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug show job inputs
      shell: bash
      run: |
        pwd
        ls -al
        ls ./scripts/badges/
        ls ./reports/
        ./scripts/badges/testresults_badge_label.sh

    - name: Set filename prefix
      shell: bash
      id: filename
      run: |
        echo "::set-output name=prefix::AltiusRupert_rbarrow-dev-ed_master"

    - name: Get Test Results
      id: testresults
      shell: bash
      run: |
        echo "::set-output name=badge_label::$(./scripts/badges/testresults_badge_label.sh)"
    - name: Get Code Coverage
      id: codecoverage
      shell: bash
      run: |
        echo "::set-output name=badge_label::$(./scripts/badges/codecoverage_badge_label.sh)"
    - name: Get PMD Analysis
      id: pmd
      shell: bash
      run: |
        echo "::set-output name=badge_label::$(./scripts/badges/pmd_badge_label.sh)"
    - name: Get Health Check
      id: healthcheck
      shell: bash
      run: |
        echo "::set-output name=badge_label::$(./scripts/badges/healthcheck_badge_label.sh)"

