name: Run Salesforce tests and save results

inputs:
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: false
  salesforce_username:
    description: Salesforce org admin username
    required: false
  salesforce_password:
    description: Salesforce org admin password, concatenated with security token
    required: false
  github_action_path:
    description: github action_path
    required: false

#outputs:
#  res:
#    value: "${{ steps.runtests.outputs.res }}"

runs:
  using: "composite"
  steps:        
      
    - name: Get last version of git
      id: getgit
      shell: bash
      run: |
        apt-get update && apt-get install software-properties-common -y && apt-add-repository ppa:git-core/ppa && apt-get update && apt-get install -y git

    - run: |
        echo "${{ github.action_path }}"
        ls -al ${{ github.action_path }}
      shell: bash

    - name: Dump github context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Run tests
      id: runtests
      shell: bash
      env:
        ACTION_PATH: "/__w/_actions/AltiusRupert/actions/main/action-run-salesforce-tests"
      run: |
        bash $ACTION_PATH/scripts/run-salesforce-tests.sh -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }}
