name: Run Salesforce tests and save results

inputs:
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: false
  salesforce_username:
    description: Salesforce org admin username
    required: false
  salesforce_password:
    description: Salesforce org admin password, concatenated with security token

outputs:
  res:
    value: "${{ steps.runtests.outputs.res }}"

runs:
  using: "composite"
  steps:        
      
    - name: Get last version of git
      id: getgit
      shell: bash
      run: |
        $( apt-get update && apt-get install software-properties-common -y && apt-add-repository ppa:git-core/ppa && apt-get update && apt-get install -y git )

    - name: Run tests
      id: runtests
      shell: bash
      run: |
        echo "::set-output name=res::$( bash ${{ github.action_path }}/scripts/run-salesforce-tests.sh -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} )"
#        $( echo ${{ github.action_path }}; ls -al ${{ github.action_path }} )
#        $( bash ${{ github.action_path }}/scripts/run-salesforce-tests.sh -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} )
