name: Populate Github repository from Salesforce org

# Salesforce login parameters.
# Login with :
# - either salesforce_url, salesforce_username, salesforce_password and salesforce_security_token
# - or salesforce_url, salesforce_username, salesforce_password without salesforce_security_token
# - or salesforce_sfdx_auth_url (get this with : sfdx force:org:display -u bprofilers-prod --verbose)
# - (tbc : or with salesforce_accesstoken)

inputs:
  # NB : checkout on the branch must be done by the caller
  contents:
    description: Contents of the package.xml
    required: true
  path:
    description: Path to the file, eg manifest/package.xml
    required: true

runs:
  using: "composite"
  steps:
    # NB : checkout on the branch must be done by the caller
    # NB : caller must set "permissions: contents: write" to allow this action to commit to Github

    #################################################################################################################################
    # GENERATE package.xml
    #

    - name: Generate package.xml content
      id: generate-xml
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const API_VERSION = 56.0

          const XML_START = `<?xml version="1.0" encoding="UTF-8"?>
          <Package xmlns="http://soap.sforce.com/2006/04/metadata">`

          const XML_END = `
            <version>${API_VERSION}</version>
          </Package>`

          const data = ${{ inputs.contents }}
          //console.log("data=", data)
          //console.log("entries=", Object.entries(data))

          let result = ''
          for(const [key, rows] of Object.entries(data)) {
          //console.log('rows=', rows)
            result += rows.map(row=>`
            <types>
              <members>${row.name}</members>
              <name>${key}</name>
            </types>`).join('')
          }

          return XML_START + result + XML_END

    - name: Update package.xml file
      shell: bash
      run: |
        echo '${{steps.generate-xml.outputs.result}}'
        echo '${{steps.generate-xml.outputs.result}}' > "${{ inputs.path }}"
