name: Git2DevopsCenter create issue

inputs:
  salesforce_sfdx_auth_url:
    description: Salesforce SFDX auth URL
    required: true
  subject:
    description: Issue subject
    required: true

runs:
  using: "composite"
  steps:
    - name: Create issue
      shell: bash
      run: |
        set -x
        cd .github/workflows/sfdx-project
        echo ${{ inputs.salesforce_sfdx_auth_url }} > ./sfdxauthurl.txt
        sfdx force:auth:sfdxurl:store -f ./sfdxauthurl.txt -s -a checkout
        rm -f ./sfdxauthurl.txt
        sfdx force:data:record:create -s sf_devops__Work_Item__c -v "sf_devops__Subject__c='${{ inputs.subject }}'"
