name: Git2DevopsCenter create issue

inputs:
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: true
  subject:
    description: Issue subject
    required: true

runs:
  using: "composite"
  steps:
    - name: Store SFDX auth URL and authenticate
      shell: bash
      run: |
        echo ${{ inputs.salesforce_sfdx_auth_url }} > ./sfdxauthurl.txt
        sfdx force:auth:sfdxurl:store -f ./sfdxauthurl.txt -s -a checkout
        sfdx force:config:set defaultusername=devopscenter
        rm -f ./sfdxauthurl.txt

    - name: Create issue
      shell: bash
      run: |
        sfdx data:record:create -s sf_devops__Work_Item__c -v "sf_devops__Subject__c='${{ inputs.subject }}'" -u devopscenter
