name: Populate Github repository from Salesforce org

# Salesforce login parameters.
# Login with :
# - either salesforce_url, salesforce_username, salesforce_password
# - or with salesforce_accesstoken
# - or with salesforce_authurl

inputs:
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: false
  salesforce_username:
    description: Salesforce org admin username
    required: false
  salesforce_password:
    description: Salesforce org admin password, concatenated with security token
    required: false
  folder_to_commit:
    description: Which folder should we commit to Git, default being .
    default: .
    required: false
  do_git_add:
    description: Do you want to git add ?
    default: false
    required: false
  do_git_commit:
    description: Do you want to git commit ?
    default: false
    required: false

runs:
  using: "composite"
  steps:        
        
    - name: Add SFDX Powerkit Plugin for login with username and password, including security token
      if: inputs.salesforce_password != ''
      shell: bash
      run: |
        echo 'y' | sfdx plugins:install sfpowerkit
        sfdx sfpowerkit:auth:login -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} -a checkout

    - name: Retrieve source from Salesforce organization
      shell: bash
      run: |
        sfdx force:config:set defaultusername=checkout        
        sfdx force:source:retrieve -x ./manifest/package.xml
        cd ./force-app/main/default/staticresources
        find . -name .git -type d -exec rm -rf {} \; || true
        cd ../../../../

    - name: Update container version of git, and commit results to Git
      if: ${{ inputs.do_git_add }} || ${{ inputs.do_git_commit }}
      shell: bash
      run: |
        apt-get update && apt-get install software-properties-common -y && apt-add-repository ppa:git-core/ppa && apt-get update && apt-get install -y git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: git add ?
      if: ${{ inputs.do_git_add }}
      shell: bash
      run: git add ${{ inputs.folder_to_commit }}

    - name: git commit ?
      if: ${{ inputs.do_git_commit }}
      shell: bash
      run: git commit -m "Updated from Salesforce" || true
