on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      flow-name:
        required: true
        type: string
    secrets:
      dev-hub-auth-url:
        required: true

jobs:
  feature-test:
    name: "Run Flow in scratch org"
    runs-on: ubuntu-latest
    steps:
      - uses: RupertBarrow/cumulus-action-run-flow-scratch@main
        with:
          dev-hub-auth-url: "${{ secrets.dev-hub-auth-url }}"
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
          flow-name: "${{ inputs.flow-name }}"
