# Remember to update also cci-standard-workflow-run-flow-scratch-packaging.yml
on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
        default: 3.69.0
      sfdx-version:
        required: false
        type: string
        default: 7.175.0
      org-name:
        required: false
        type: string
        default: dev
      flow-name:
        required: true
        type: string
      flow-task-options:
        required: false
        type: string
    secrets:
      dev-hub-auth-url:
        required: true
      cumulusci-service-github:
        required: true

jobs:
  run-flow-scratch:
    name: "Run Flow in scratch org"
    runs-on: ubuntu-latest
    steps:
      - uses: RupertBarrow/cumulus-action-run-flow-scratch@main
        with:
          dev-hub-auth-url: "${{ secrets.dev-hub-auth-url }}"
          cumulusci-service-github: "${{ secrets.cumulusci-service-github }}"
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
          flow-name: "${{ inputs.flow-name }}"
          flow-task-options: "${{ inputs.flow-task-options }}"
          org-name: "${{ inputs.org-name }}"
