on:
  workflow_call:

job:
  test_summary:
    name: Test Summary
    uses: test-summary/action@v2
    with:
      paths: "reports/test-results.xml"
    if: always()

  upload_test_summary:
    name: Upload test summary
    uses: actions/upload-artifact@v3
    with:
      name: test-summary
      path: reports/TESTS.md
    if: always()
