name: Run command

# Salesforce login parameters.
# Login with : salesforce_sfdx_auth_url (get this with : sfdx force:org:display -u myorg --verbose)

inputs:
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: false
  salesforce_sfdx_auth_url:
    description: Salesforce SFDX auth URL
    required: false
  home:
    description: Set HOME env variable (default is /github/home)
    default: "/github/home"
    required: false
  command:
    description: run this command (sfdx or other) in bash
    required: true

runs:
  using: "composite"
  steps:
    # NB : checkout on the branch must be done by the caller

    #################################################################################################################################
    # AUTHENTICATION
    #

    - name: Authenticate with SF
      shell: bash
      run: |
        export HOME=${{ inputs.home }}
        if [ -z "${{ inputs.salesforce_sfdx_auth_url }}" ]
        then
          echo "ERROR : Salesforce DX auth url is mandatory"
          exit 1
        else
          echo sf org login sfdx-url --set-default --alias checkout
          sf org login sfdx-url --set-default --alias checkout -f <(echo "${{ inputs.salesforce_sfdx_auth_url }}")
        fi

    #################################################################################################################################
    # Run command (sf, sfdx or other)
    #

    - name: Run command ${{ inputs.command }}
      id: command
      shell: bash
      run: |
        set -x
        export HOME=${{ inputs.home }}
        echo result='$( ${{ inputs.command }} )' >> "$GITHUB_OUTPUT"
        echo $result

    - name: Output command result to an annotation
      uses: dkhunt27/action-annotations@v1
      with:
        type: notice
        msg: ${{ steps.command.outputs.result }}
