name: Run command

# Salesforce login parameters.
# Login with :
# - either salesforce_url, salesforce_username, salesforce_password and salesforce_security_token
# - or salesforce_url, salesforce_username, salesforce_password without salesforce_security_token
# - or salesforce_sfdx_auth_url (get this with : sfdx force:org:display -u bprofilers-prod --verbose)
# - (tbc : or with salesforce_accesstoken)

inputs:
  # NB : checkout on the branch must be done by the caller

  # Authentication
  salesforce_url:
    description: Salesforce org url (best with mydomain.my.salesforce.com, mydomain-dev-ed.my.salesforce ou mydomain--mysandbvox.my.salesforce.com
    required: false
  salesforce_username:
    description: Salesforce org admin username
    required: false
  salesforce_password:
    description: Salesforce org admin password
    required: false
  salesforce_security_token:
    description: Salesforce security toker
    required: false
  salesforce_sfdx_auth_url:
    description: Salesforce SFDX auth URL
    required: false

  # command
  command:
    description: run this command (sfdx or other) in bash
    required: true

runs:
  using: "composite"
  steps:
    # NB : checkout on the branch must be done by the caller

    #################################################################################################################################
    # AUTHENTICATION
    #

    - name: Store SFDX auth URL
      shell: bash
      run: |
        echo ${{ inputs.salesforce_sfdx_auth_url }} > ./sfdxauthurl.txt

    - name: Authenticate
      shell: bash
      run: |
        if [ -z "${{ inputs.salesforce_sfdx_auth_url }}" ]
        then
          echo 'y' | sfdx plugins add sfpowerkit
          if [ -z "${{ inputs.salesforce_security_token }}" ]
          then
            echo sfdx sfpowerkit:auth:login -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} -a checkout
            sfdx      sfpowerkit:auth:login -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} -a checkout
          else
            echo sfdx sfpowerkit:auth:login -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} -s ${{ inputs.salesforce_security_token }} -a checkout
            sfdx      sfpowerkit:auth:login -r ${{ inputs.salesforce_url }} -u ${{ inputs.salesforce_username }} -p ${{ inputs.salesforce_password }} -s ${{ inputs.salesforce_security_token }} -a checkout
          fi
        else
          echo sfdx auth sfdxurl store -f ./sfdxauthurl.txt -s -a checkout
          sfdx auth sfdxurl store -f ./sfdxauthurl.txt -s -a checkout
        fi
        sfdx config set defaultusername=checkout
        rm -f ./sfdxauthurl.txt

    #################################################################################################################################
    # Run command (sfdx or other)
    #

    - name: Run command ${{ inputs.command }}
      shell: bash
      run: |
        ${{ inputs.command }}
